import { NextResponse } from 'next/server';

const quotes = [
  // --- CLASSIC WISDOM ---
  { description: "Time spent with cats is never wasted.", name: "Sigmund Freud" },
  { description: "In ancient times cats were worshipped as gods; they have not forgotten this.", name: "Terry Pratchett" },
  { description: "What greater gift than the love of a cat?", name: "Charles Dickens" },
  { description: "Cats choose us; we don’t own them.", name: "Kristin Cast" },
  { description: "A cat has absolute emotional honesty.", name: "Ernest Hemingway" },
  { description: "The smallest feline is a masterpiece.", name: "Leonardo da Vinci" },
  { description: "Cats are connoisseurs of comfort.", name: "James Herriot" },
  { description: "There are two means of refuge from the miseries of life: music and cats.", name: "Albert Schweitzer" },
  { description: "A house is not a home without a cat.", name: "Unknown" },
  { description: "Cats leave paw prints on your heart forever.", name: "Unknown" },

  // --- FUNNY & SASSY ---
  { description: "I’m not lazy, I’m just on energy-saving mode.", name: "A Tired Ginger" },
  { description: "If cats could talk, they wouldn’t.", name: "Nan Porter" },
  { description: "Dogs have owners, cats have staff.", name: "Local Tabby" },
  { description: "I had a dream I was a dog. It was a nightmare.", name: "Sophisticated Siamese" },
  { description: "Does this fur make me look fat?", name: "Every Cat Ever" },
  { description: "To err is human, to purr is feline.", name: "Robert Byrne" },
  { description: "Silence is golden. Unless you have a cat, then it's suspicious.", name: "Cat Mom" },
  { description: "If I fits, I sits.", name: "The Law of Physics" },
  { description: "The cat is always on the wrong side of the door.", name: "Feline Logic" },
  { description: "I’m not a cat person... I’m a cat's person.", name: "Anonymous" },

  // --- COZY & SWEET ---
  { description: "A purr is the sound of a happy soul.", name: "Kitty Wisdom" },
  { description: "Soft fur, warm heart.", name: "A Fluffy Calico" },
  { description: "Everything is better with a cat on your lap.", name: "Cozy Home" },
  { description: "The road to my heart is paved with paw prints.", name: "Anonymous" },
  { description: "A cat’s purr is the best lullaby.", name: "Night Owl" },
  { description: "Home is where the cat is.", name: "Homebody" },
  { description: "Life is purr-fect with you around.", name: "Best Friend" },
  { description: "Sunlight and a cat make the best afternoon.", name: "A Lazy Sunday" },
  { description: "A kitten is the rosebud of the garden of the world.", name: "Robert Southey" },
  { description: "Kittens are angels with whiskers.", name: "Unknown" },

  // --- CAT PHILOSOPHY ---
  { description: "Life is short. Sleep 16 hours a day.", name: "Zen Master Cat" },
  { description: "Always land on your feet, no matter what happens.", name: "The Acrobat" },
  { description: "The best things in life are furry.", name: "Nature Lover" },
  { description: "Meow is more than a word; it’s a lifestyle.", name: "The Philosopher" },
  { description: "Every cat is a lion in his own duplex.", name: "Yiddish Proverb" },
  { description: "Cats know how to obtain food without labor, shelter without confinement, and love without penalties.", name: "W. L. George" },
  { description: "One cat just leads to another.", name: "Ernest Hemingway" },
  { description: "The way to get on with a cat is to treat it as an equal.", name: "Louis J. Camuti" },
  { description: "Cats are intended to teach us that not everything in nature has a purpose.", name: "Garrison Keillor" },
  { description: "You cannot look at a sleeping cat and feel tense.", name: "Jane Pauley" },

  // --- 60 MORE MIXED QUOTES (Shortened for display) ---
  { description: "I am the master of this house.", name: "Black Cat" },
  { description: "No house is complete without the pitter-patter of kitty feet.", name: "Unknown" },
  { description: "Cats possess a sovereign indifference.", name: "F.A. Paradis de Moncrif" },
  { description: "My cat is not a pet, he is family.", name: "Proud Owner" },
  { description: "Whiskers are the cat's radar.", name: "Science Cat" },
  { description: "A cat will be your friend if you are worthy of its friendship.", name: "Unknown" },
  { description: "You don't own a cat. You're just renting the space.", name: "Reality Check" },
  { description: "The cat is the only animal which has managed to untame man.", name: "Marcel Mauss" },
  { description: "Cats are the ultimate introverts.", name: "Meow Guru" },
  { description: "A cat is a puzzle for which there is no solution.", name: "Hazel Nicholson" },
  { description: "Happiness is a warm kitten.", name: "Charles Schultz" },
  { description: "The cat does not offer services. The cat offers itself.", name: "William S. Burroughs" },
  { description: "If you want the best seat in the house, move the cat.", name: "Proverb" },
  { description: "Cats are mysterious; they have more in their minds than we can imagine.", name: "Walter Scott" },
  { description: "A cat can purr its way out of anything.", name: "Donna McCrohan" },
  { description: "In a cat's eye, all things belong to cats.", name: "English Proverb" },
  { description: "One is never lonely with a cat.", name: "Colette" },
  { description: "Cats are smarter than dogs. You can't get eight cats to pull a sled.", name: "Jeff Valdez" },
  { description: "A kitten is chiefly remarkable for rushing about like mad.", name: "Agnes Repplier" },
  { description: "The cat is the soul of the home.", name: "French Saying" },
  { description: "I love my cats more than I love most people.", name: "Honest Human" },
  { description: "Cats are a mysterious kind of folk.", name: "Sir Walter Scott" },
  { description: "A cat’s life is the best life.", name: "Nap King" },
  { description: "Feed me, pet me, then leave me alone.", name: "The Cat Code" },
  { description: "A cat is just a small tiger that lives in your house.", name: "Jungle Cat" },
  { description: "Every house should have a resident feline.", name: "Interior Designer" },
  { description: "Cats are the masters of zen.", name: "Meditation Cat" },
  { description: "My cat is my shadow.", name: "Shadow Hunter" },
  { description: "A cat is better than any alarm clock.", name: "6 AM Cat" },
  { description: "Purring is the sound of contentment.", name: "Happy Tails" },
  { description: "Life without cats is like a library without books.", name: "Scholar" },
  { description: "A cat’s eyes are windows to another world.", name: "Stargazer" },
  { description: "Cats are the quiet kings of the world.", name: "Royal Feline" },
  { description: "My cat understands me better than I do.", name: "Deep Thinker" },
  { description: "A cat is a little piece of magic.", name: "Wizard Cat" },
  { description: "Whiskers make everything better.", name: "Style Icon" },
  { description: "Paws, purrs, and perfection.", name: "Kitty Lover" },
  { description: "Cats are the stars of the internet.", name: "Social Media Star" },
  { description: "A cat is a friend for life.", name: "Loyal Companion" },
  { description: "Cats are the true keepers of secrets.", name: "Spy Cat" },
  { description: "My cat is my heart.", name: "Sweet Soul" },
  { description: "A cat is a bundle of joy and fur.", name: "Playful Kitten" },
  { description: "Cats are the ultimate decorators.", name: "Home Stylist" },
  { description: "A cat’s love is unconditional (mostly).", name: "Food Provider" },
  { description: "Cats are the guardians of the night.", name: "Moonlight Hunter" },
  { description: "My cat is my favorite person.", name: "Introvert Life" },
  { description: "A cat is a symphony of purrs.", name: "Musician Cat" },
  { description: "Cats are the poetry of motion.", name: "Dancer Cat" },
  { description: "A cat is a masterpiece in every way.", name: "Art Critic" },
  { description: "Cats are the ultimate adventure partners.", name: "Explorer Cat" },
  { description: "My cat is my spirit animal.", name: "Spirit Guide" },
  { description: "A cat is a blessing in disguise.", name: "Grateful Heart" },
  { description: "Cats are the rulers of the universe.", name: "Space Cat" },
  { description: "A cat’s purr can heal the soul.", name: "Healer Cat" },
  { description: "My cat is the reason I smile.", name: "Happy Human" },
  { description: "A cat is a gift from the universe.", name: "Cosmic Kitty" },
  { description: "Cats are the true meaning of grace.", name: "Graceful Feline" },
  { description: "A cat is a constant source of wonder.", name: "Dreamer Cat" },
  { description: "My cat is my best adventure.", name: "Travel Cat" },
  { description: "A cat is the ultimate companion.", name: "Forever Friend" }
];
export async function GET() {
  const randomQuote = quotes[Math.floor(Math.random() * quotes.length)];
  return NextResponse.json(randomQuote);
}